### ISSUE TITLE
hic_breakfinder won't compile

### ISSUE THREAD

**Issue by jacel** [dixonlab/hic_breakfinder#6]
Hi, I'm having some issues compiling this code

Firstly, the current bamtools installation creates the folder: /usr/local/include/bamtools/api, so I had to create a symlink to api and shared in usr/local/include. Once that was fixed, I now get a whole bunch of new errors:

g++  -g -O2 -g  -o hic_breakfinder hic_breakfinder.o  -lbamtools
//usr/local/lib/libbamtools.a(BgzfStream_p.cpp.o): In function `BamTools::Internal::BgzfStream::DeflateBlock(int)':
BgzfStream_p.cpp:(.text+0x1a9): undefined reference to `deflateEnd'
BgzfStream_p.cpp:(.text+0x211): undefined reference to `deflateInit2_'
BgzfStream_p.cpp:(.text+0x22a): undefined reference to `deflate'
BgzfStream_p.cpp:(.text+0x240): undefined reference to `deflateEnd'
BgzfStream_p.cpp:(.text+0x279): undefined reference to `crc32'
BgzfStream_p.cpp:(.text+0x286): undefined reference to `crc32'
//usr/local/lib/libbamtools.a(BgzfStream_p.cpp.o): In function `BamTools::Internal::BgzfStream::InflateBlock(unsigned long const&)':
BgzfStream_p.cpp:(.text+0xe8c): undefined reference to `inflateInit2_'
BgzfStream_p.cpp:(.text+0xe9d): undefined reference to `inflate'
BgzfStream_p.cpp:(.text+0xeae): undefined reference to `inflateEnd'
BgzfStream_p.cpp:(.text+0xf72): undefined reference to `inflateEnd'
BgzfStream_p.cpp:(.text+0xff4): undefined reference to `inflateEnd'
collect2: error: ld returned 1 exit status

I found a bug report that seems to report exactly the same issue, and it seems as if the code has been developed with bamtools 2.4 and is not compatible with the current version (2.5.1).
https://github.com/AstraZeneca-NGS/disambiguate/issues/10

Do you have any suggestions other than using bamtools 2.4?

Thanks!
Elsie

**Comment by dixonlab** [comment]
Hi Elsie,
Thanks for bringing this to my attention, I have not seen this before. I can look into updating the code to use the most recent version of bamtools. In the meantime, the best solution would probably be to try to compile using bam tools 2.4.

**Comment by jacel** [comment]
Hi Jesse,
No problem, It seems to be working now with bamtools 2.4.0. Thanks for making the tool so usable! I was excited to run it on my data as soon as I saw your paper. 
Cheers,
Elsie

**Comment by ghost** [comment]
Hi Jacel,
Can you help me out with this installation of bamtools, i am also facing the same problem and couldn't find any way out yet.
That would be so kind of you.
Madiha

**Comment by jacel** [comment]
Hi Madiha,
When I tried this last year, I needed exactly bamtools 2.4.0 (not 2.4.1 or 2.4.x) - do you have this version installed?
Cheers,
Elsie

**Comment by ghost** [comment]
Thank you for your response.
I have 2.5.1. build is fine, etc., still, at the end at compiling phase I get error  "fatal error: api/BamReader.h: No such file or directory
compilation terminated."
 This is my compiling command
g++ main.cpp -L  /softwares/bamtools-build/lib -I /softwares/bamtools-build/include -lbamtools -lz
Problem is include file don't have api/.h files in build folder, and source folder dosent have include. So, i am not sure which path should be provided for -I. I copied paste api etc folders from source folder to build/include (not sure this manual moving of folders can work)


Regards,
Madiha Shabbir

________________________________

**Comment by jacel** [comment]
Hi Madiha,
I remember trying to play around with the file structure in bamtools 2.5 (6 months ago - I don't remember exactly what I did sorry), but kept coming up against errors. In the end I did what Jesse suggested and just installed hic_breakfinder with bamtools 2.4.0. All the files and folders are in the right place and it works nicely!  

Good luck,
Elsie Jacobson

**Comment by ghost** [comment]
Hi Jacel,
Thank you, I have tried 2.4.0 now everything seems fine as you said all files and folders are at right place. Still, I am unable to link it to my .cpp file through #include. I am using Netbeans compiler.
Do you have anything to guide me in this compilation phase?

**Comment by jacel** [comment]
Hi Madiha,
Are you following the instructions in the README of this repository? I haven't used Netbeans before, but this installation doesn't require an IDE. Can you try to install it on the command line:

./configure CPPFLAGS="-I /path/to/bamtools/include -I /path/to/eigen" LDFLAGS="-L/path/to/bamtools/lib/"

Make sure you have the eigen c++ library installed as well:
(http://eigen.tuxfamily.org/index.php?title=Main_Page)

**Comment by dixonlab** [comment]
Hi Madiha and Elsie,
I haven't tried to compile using Netbeans before. I'm honestly not all that familiar with this compiler. What machine/operating system are you trying to install this on? 
-Jesse

**Comment by ghost** [comment]
Thank you Jacel and Jesse for your help and time.
I installed eigen and tried your way but it didn't make any difference. But I had figured out through this that my installation is perfect now and the only problem is integrating it with the compiler as an external library. Well, I am able to resolve that issue as well by changing configurations of the compiler manually.
Finally in peace :)
Thank you guys once again.

Best,
Maidha
